<?php
/**
 * @category    Aligent
 * @package     Aligent_WebsiteSwitcher
 * @copyright   Copyright (c) 2013 Aligent Consulting. (http://www.aligent.com.au)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author         Luke Mills <luke@aligent.com.au>
 */

/** @var $this Aligent_WebsiteSwitcher_Block_Switcher */
?>
<div id="aligent-switcher" class="white-box white-lightbox">
    <h1><?php echo $this->__('Welcome'); ?></h1>

    <p><?php echo $this->__("You are visiting <strong>%s</strong>", $this->getCurrentStoreName()); ?></p>
    <br/>

    <p><?php echo $this->__("If this is incorrect, please select you're location:"); ?></p>
    <br/>

    <?php echo $this->getLayout()->createBlock('aligent_websiteswitcher/switcher')->setTemplate('aligent/websiteswitcher/switcher.phtml')->toHtml(); ?>
    <br/>
    <p><?php echo $this->__('Do you still want to continue?'); ?>
    <a href="<?php echo $this->getCurrentStore()->getCurrentUrl()?>"><?php echo $this->__('Click Here'); ?></a></p>
</div>
<script type="text/javascript">
    //<![CDATA[
    document.observe('dom:loaded', function() {
        if($('aligent-switcher')){
            $jQ('#aligent-switcher').lightbox_me({
                centered: true
            });
        }
        Event.stop(event);
    });
    //]]>
</script>