<?php
/**
 * @category    Aligent
 * @package     Aligent_WebsiteSwitcher
 * @copyright   Copyright (c) 2013 Aligent Consulting. (http://www.aligent.com.au)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author         Luke Mills <luke@aligent.com.au>
 * @author      Swapna Palaniswamy <swapna@aligent.com.au>
 * @author      Jim O'Halloran <jim@aligent.com.au>
 */

/** @var $this Aligent_WebsiteSwitcher_Block_Switcher */
?>
<div id="aligent-switcher" class="white-box white-lightbox" style="display: none;">
    <h1><?php echo $this->__('Welcome'); ?></h1>
    <?php echo $this->__("You are visiting <strong>%s</strong>", $this->getCurrentStoreName()); ?>

    <p class="continue"><a href="<?php echo $this->getCurrentStore()->getCurrentUrl()?>"><?php echo $this->__('Continue'); ?></a> </p>

    <p><?php echo $this->__("If this is incorrect, please select your location:"); ?></p>

    <?php echo $this->getChildHtml('modal_switcher'); ?>

</div>

<script type="text/javascript">
    //<![CDATA[

    var ShowWebsiteSwitcher = Class.create({
        initialize: function() {
            document.observe('dom:loaded', this.handleLoad.bind(this));
        },
        handleLoad: function() {
            var vClientCookieName = 'store_selected';
            // Parse client side cookie to see if we've popped the modal before.
            var aClientResults = document.cookie.match ( '(^|;) ?' + vClientCookieName + '=([^;]*)(;|$)' );

            if (!aClientResults && $('aligent-switcher')) {
                // Set the client side cookie to indicate that the modal has been displayed.
                var setValue = vClientCookieName + '=1';
                var expiryDate = new Date();
                expiryDate.setTime(expiryDate.getTime()+(365*24*60*60*1000)); // 365 days
                var setExpiration = "; expires="+expiryDate.toGMTString();
                var setCookiePath = "; path=/";  // Make this cookie the same on all pages for this site
                document.cookie = setValue+setExpiration+setCookiePath;
                this.showWebsiteSwitcher();
            }
        },
        showWebsiteSwitcher: function() {
            var contentWin = null;
            contentWin = new Window({
                className: 'aligent',
                recenterAuto: false,
                maximizable: false,
                minimizable: false,
                resizable: false,
                hideEffect: Element.hide,
                showEffect: Element.show,
                minWidth: 240,
                destroyOnClose: true
            });
            contentWin.setContent('aligent-switcher', true, false);
            contentWin.setZIndex(20);
            contentWin.showCenter(true);
            $$('#aligent-switcher .continue')[0].observe('click', function (event) {
                contentWin.close();
                event.stop();
            });
        }
    });

    var websiteSwitcher = new ShowWebsiteSwitcher();
    //]]>
</script>