<?php
/**
 * @category    Aligent
 * @package     Aligent_WebsiteSwitcher
 * @copyright   Copyright (c) 2013 Aligent Consulting. (http://www.aligent.com.au)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author 		Luke Mills <luke@aligent.com.au>
 */

/** @var $this Aligent_WebsiteSwitcher_Block_Switcher */
?>
<?php
$_stores = $this->getStores();
?>
<div class="form-website">
    <label for="select-website"><?php echo $this->__('Select website:') ?></label>    
    <select id="select-website" title="<?php echo $this->__('Select website:') ?>" onchange="window.location.href=this.value">
        <?php foreach ($_stores as $_store) : ?>
            <?php $_selected = ($_store->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
            <option value="<?php echo $_store->getCurrentUrl() ?>"<?php echo $_selected ?>><?php echo $this->escapeHtml($_store->getName()) ?></option>
        <?php endforeach; ?>
    </select>
</div>
