<?php
/**
 * app/design/frontend/base/default/template/aligent/websiteswitcher/switcher.phtml
 *
 * @category  Aligent
 * @package   Aligent_WebsiteSwitcher
 * @author    Luke Mills <luke@aligent.com.au>
 * @author    Jim O'Halloran <jim@aligent.com.au>
 * @copyright 2013-2014 Aligent Consulting.
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.aligent.com.au/
 */

/** @var $this Aligent_WebsiteSwitcher_Block_Switcher */
?>
<?php
$_stores = $this->getStores();
?>
<div class="form-website">
    <label for="select-website"><?php echo $this->__('Select website:') ?></label>
    <select id="select-website" title="<?php echo $this->__('Select website:') ?>">
        <?php foreach ($_stores as $_store) : ?>
            <?php $_selected = ($_store->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
            <option value="<?php echo $_store->getCurrentUrl() ?>"<?php echo $_selected ?>>
                <?php echo $this->escapeHtml($_store->getName()) ?>
            </option>
        <?php endforeach; ?>
    </select>

    <a href="javascript:void(0)" onclick="window.location.href=document.getElementById('select-website').value;">
        <?php echo $this->__('Change'); ?>
    </a>

</div>
